### ISSUE TITLE
:extrema fails if all values are equal

### ISSUE THREAD

**Issue by SimonWoods** [JuliaGraphics/ColorSchemes.jl#43] opened 2020-09-14 22:27 UTC
If all array values are equal, using `get` with the `:extrema` option gives an error.

    get(colorschemes[:sunset], fill(0.3,20,20), :extrema)

    ERROR: InexactError: trunc(Int64, NaN)

It would be nice if this edge case was handled.

**Comment by cormullion** [comment] 2020-09-15 08:17
Hi Simon  (I remember your amazing contributions to the Mathematica Stack Exchange?)... 

Looks like the problem is with `remap` [here](https://github.com/JuliaGraphics/ColorSchemes.jl/blob/542b4aaadb9d046d2e9d3fc04192d1105dc05e26/src/ColorSchemes.jl#L206)

so:

```
remap(x, 0.3, 0.3, 1, 10)
2-element Array{Float64,1}:
 NaN
 NaN
```

I suppose it could be fixed by inserting 

```
iszero(first(rangescale) - last(rangescale)) && error("Empty rangescale: $(rangescale)")
```

at the start of that function, without too much of a penalty...

**Comment by SimonWoods** [comment] 2020-09-19 16:06
Hi Cormullion, yes that's me. I haven't been active there for a while, most of my hobby programming is in Julia these days.

I'd argue for `get` to still return an image (albeit a boring one) when the array values are all equal. Maybe use the midpoint of the colour scheme?

**Closed** 2020-09-28 08:16 UTC
